version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: pg-testbd
    environment:
      - POSTGRES_DB=testbd
      - POSTGRES_USER=admin
      - POSTGRES_HOST_AUTH_METHOD=trust # Desabilita autenticação (APENAS PARA DEV)
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d testbd"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
